### PR TITLE
fix: investigated yen currency display

### LINKED ISSUE #269: Investigate why japanese yen is displaying differently
Previously, 100 Japanese Yen was represented as `¥100`, now, it's represented as `JP¥100`

Figure out _why_ this is happening, if it's a problem, and what other currencies have been affected

### PR DESCRIPTION
**Pull request by avery-clark**
🎟️ fixes #269

### Description

Fixes `Money` so that currencies which have other than two decimal places will be displayed correctly. Also added comments to aid precision of understanding.

### How Has This Been Tested?

Added tests which run and pass.

### Notes

I feel as though an explanation of the terms main unit and subunit could be useful for additional context, but I'm not sure it's appropriate to add even more comments. Opinions on the readability of the content of the files (esp. comments )would be much appreciated.

### CODE REVIEW

File: src/Money.ts [hunk 1]
```diff
@@ -34,12 +40,12 @@ export default class Money {
...
-   * Parse monetary string value
-   * @param string input
-   * @param string currency
+   * Create a Money object from a string representation of the amount of money
+   * @param mainAmount The quantity of money as a string in the main unit of the currency (e.g. '10.50' for £10.50)
+   * @param currency The alphabetic currency code as defined by ISO 4217 (e.g. GBP for Sterling)
    */
-  static fromString(input: string, currency: string) {
-    const amount = parseCurrencyString(input, currency)
+  static fromString(mainAmount: string, currency: string): Money {
```
Comment (andrewdavidcostello) [inline src/Money.ts:47]: Can we rename mainAmount back to input here please.

Comment (avery-clark) [reply src/Money.ts]: No problem can do, can I ask why `input` is preferred? (ee530e791ec2e14dddb3b4e5a4e4d41f51deb137)

Comment (andrewdavidcostello) [reply src/Money.ts]: It is mostly because when we refer to the term `amount` it is a number, by using input we a creating a clear difference that it is a string representation input to a money object that needs parsing and converting to an amount.

**Review by andrewdavidcostello — APPROVED** [review]
LGTM!
